#!/bin/sh

echo building types...
tsc --outDir types --declaration --emitDeclarationOnly &&  \
  echo built types...
  rm -rf types
  mv types/code-generator/src/* types/
  rm -rf types/code-generator


